// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enfonica/numbering/v1beta1/phone_number_instances.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Enfonica.Numbering.V1Beta1 {

  /// <summary>Holder for reflection information generated from enfonica/numbering/v1beta1/phone_number_instances.proto</summary>
  public static partial class PhoneNumberInstancesReflection {

    #region Descriptor
    /// <summary>File descriptor for enfonica/numbering/v1beta1/phone_number_instances.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PhoneNumberInstancesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjdlbmZvbmljYS9udW1iZXJpbmcvdjFiZXRhMS9waG9uZV9udW1iZXJfaW5z",
            "dGFuY2VzLnByb3RvEhplbmZvbmljYS5udW1iZXJpbmcudjFiZXRhMRofZ29v",
            "Z2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90bxogZ29vZ2xlL3Byb3RvYnVm",
            "L2ZpZWxkX21hc2sucHJvdG8aHGdvb2dsZS9hcGkvYW5ub3RhdGlvbnMucHJv",
            "dG8aLmVuZm9uaWNhL251bWJlcmluZy92MWJldGExL3Bob25lX251bWJlcnMu",
            "cHJvdG8i0QQKE1Bob25lTnVtYmVySW5zdGFuY2USDAoEbmFtZRgBIAEoCRI9",
            "CgxwaG9uZV9udW1iZXIYAiABKAsyJy5lbmZvbmljYS5udW1iZXJpbmcudjFi",
            "ZXRhMS5QaG9uZU51bWJlchIUCgxkaXNwbGF5X25hbWUYAyABKAkSSwoGbGFi",
            "ZWxzGAQgAygLMjsuZW5mb25pY2EubnVtYmVyaW5nLnYxYmV0YTEuUGhvbmVO",
            "dW1iZXJJbnN0YW5jZS5MYWJlbHNFbnRyeRIlCh1pbmNvbWluZ19tZXNzYWdl",
            "X2hhbmRsZXJfdXJpcxgFIAMoCRIiChppbmNvbWluZ19jYWxsX2hhbmRsZXJf",
            "dXJpcxgGIAMoCRIvCgtjcmVhdGVfdGltZRgKIAEoCzIaLmdvb2dsZS5wcm90",
            "b2J1Zi5UaW1lc3RhbXASLwoLZGVsZXRlX3RpbWUYCyABKAsyGi5nb29nbGUu",
            "cHJvdG9idWYuVGltZXN0YW1wElcKD2xpZmVjeWNsZV9zdGF0ZRgMIAEoDjI+",
            "LmVuZm9uaWNhLm51bWJlcmluZy52MWJldGExLlBob25lTnVtYmVySW5zdGFu",
            "Y2UuTGlmZWN5Y2xlU3RhdGUaLQoLTGFiZWxzRW50cnkSCwoDa2V5GAEgASgJ",
            "Eg0KBXZhbHVlGAIgASgJOgI4ASJVCg5MaWZlY3ljbGVTdGF0ZRIbChdMSUZF",
            "Q1lDTEVfU1RBVEVfVU5LTk9XThAAEgoKBkFDVElWRRABEgsKB0RFTEVURUQQ",
            "AhINCglTVVNQRU5ERUQQAyKCAQogQ3JlYXRlUGhvbmVOdW1iZXJJbnN0YW5j",
            "ZVJlcXVlc3QSDgoGcGFyZW50GAEgASgJEk4KFXBob25lX251bWJlcl9pbnN0",
            "YW5jZRgCIAEoCzIvLmVuZm9uaWNhLm51bWJlcmluZy52MWJldGExLlBob25l",
            "TnVtYmVySW5zdGFuY2UiLQodR2V0UGhvbmVOdW1iZXJJbnN0YW5jZVJlcXVl",
            "c3QSDAoEbmFtZRgBIAEoCSKBAQofTGlzdFBob25lTnVtYmVySW5zdGFuY2Vz",
            "UmVxdWVzdBIOCgZwYXJlbnQYASABKAkSEQoJcGFnZV9zaXplGAIgASgFEhIK",
            "CnBhZ2VfdG9rZW4YAyABKAkSDgoGcHJlZml4GAQgASgJEhcKD2luY2x1ZGVf",
            "ZGVsZXRlZBgFIAEoCCKMAQogTGlzdFBob25lTnVtYmVySW5zdGFuY2VzUmVz",
            "cG9uc2USTwoWcGhvbmVfbnVtYmVyX2luc3RhbmNlcxgBIAMoCzIvLmVuZm9u",
            "aWNhLm51bWJlcmluZy52MWJldGExLlBob25lTnVtYmVySW5zdGFuY2USFwoP",
            "bmV4dF9wYWdlX3Rva2VuGAIgASgJIrEBCiBVcGRhdGVQaG9uZU51bWJlcklu",
            "c3RhbmNlUmVxdWVzdBIMCgRuYW1lGAEgASgJEk4KFXBob25lX251bWJlcl9p",
            "bnN0YW5jZRgCIAEoCzIvLmVuZm9uaWNhLm51bWJlcmluZy52MWJldGExLlBo",
            "b25lTnVtYmVySW5zdGFuY2USLwoLdXBkYXRlX21hc2sYAyABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuRmllbGRNYXNrIjAKIERlbGV0ZVBob25lTnVtYmVySW5z",
            "dGFuY2VSZXF1ZXN0EgwKBG5hbWUYASABKAkiUAooR2V0UHJvdmlzaW9uZWRQ",
            "aG9uZU51bWJlckluc3RhbmNlUmVxdWVzdBIOCgZwYXJlbnQYASABKAkSFAoM",
            "cGhvbmVfbnVtYmVyGAIgASgJMpsKChRQaG9uZU51bWJlckluc3RhbmNlcxLc",
            "AQoZQ3JlYXRlUGhvbmVOdW1iZXJJbnN0YW5jZRI8LmVuZm9uaWNhLm51bWJl",
            "cmluZy52MWJldGExLkNyZWF0ZVBob25lTnVtYmVySW5zdGFuY2VSZXF1ZXN0",
            "Gi8uZW5mb25pY2EubnVtYmVyaW5nLnYxYmV0YTEuUGhvbmVOdW1iZXJJbnN0",
            "YW5jZSJQgtPkkwJKIjEvdjFiZXRhMS97cGFyZW50PXByb2plY3RzLyp9L3Bo",
            "b25lTnVtYmVySW5zdGFuY2VzOhVwaG9uZV9udW1iZXJfaW5zdGFuY2USvwEK",
            "FkdldFBob25lTnVtYmVySW5zdGFuY2USOS5lbmZvbmljYS5udW1iZXJpbmcu",
            "djFiZXRhMS5HZXRQaG9uZU51bWJlckluc3RhbmNlUmVxdWVzdBovLmVuZm9u",
            "aWNhLm51bWJlcmluZy52MWJldGExLlBob25lTnVtYmVySW5zdGFuY2UiOYLT",
            "5JMCMxIxL3YxYmV0YTEve25hbWU9cHJvamVjdHMvKi9waG9uZU51bWJlcklu",
            "c3RhbmNlcy8qfRLQAQoYTGlzdFBob25lTnVtYmVySW5zdGFuY2VzEjsuZW5m",
            "b25pY2EubnVtYmVyaW5nLnYxYmV0YTEuTGlzdFBob25lTnVtYmVySW5zdGFu",
            "Y2VzUmVxdWVzdBo8LmVuZm9uaWNhLm51bWJlcmluZy52MWJldGExLkxpc3RQ",
            "aG9uZU51bWJlckluc3RhbmNlc1Jlc3BvbnNlIjmC0+STAjMSMS92MWJldGEx",
            "L3twYXJlbnQ9cHJvamVjdHMvKn0vcGhvbmVOdW1iZXJJbnN0YW5jZXMS3AEK",
            "GVVwZGF0ZVBob25lTnVtYmVySW5zdGFuY2USPC5lbmZvbmljYS5udW1iZXJp",
            "bmcudjFiZXRhMS5VcGRhdGVQaG9uZU51bWJlckluc3RhbmNlUmVxdWVzdBov",
            "LmVuZm9uaWNhLm51bWJlcmluZy52MWJldGExLlBob25lTnVtYmVySW5zdGFu",
            "Y2UiUILT5JMCSjIxL3YxYmV0YTEve25hbWU9cHJvamVjdHMvKi9waG9uZU51",
            "bWJlckluc3RhbmNlcy8qfToVcGhvbmVfbnVtYmVyX2luc3RhbmNlEsUBChlE",
            "ZWxldGVQaG9uZU51bWJlckluc3RhbmNlEjwuZW5mb25pY2EubnVtYmVyaW5n",
            "LnYxYmV0YTEuRGVsZXRlUGhvbmVOdW1iZXJJbnN0YW5jZVJlcXVlc3QaLy5l",
            "bmZvbmljYS5udW1iZXJpbmcudjFiZXRhMS5QaG9uZU51bWJlckluc3RhbmNl",
            "IjmC0+STAjMqMS92MWJldGExL3tuYW1lPXByb2plY3RzLyovcGhvbmVOdW1i",
            "ZXJJbnN0YW5jZXMvKn0S5wEKIUdldFByb3Zpc2lvbmVkUGhvbmVOdW1iZXJJ",
            "bnN0YW5jZRJELmVuZm9uaWNhLm51bWJlcmluZy52MWJldGExLkdldFByb3Zp",
            "c2lvbmVkUGhvbmVOdW1iZXJJbnN0YW5jZVJlcXVlc3QaLy5lbmZvbmljYS5u",
            "dW1iZXJpbmcudjFiZXRhMS5QaG9uZU51bWJlckluc3RhbmNlIkuC0+STAkUi",
            "QC92MWJldGExL3twYXJlbnQ9cHJvamVjdHMvKn0vcGhvbmVOdW1iZXJJbnN0",
            "YW5jZXM6Z2V0UHJvdmlzaW9uZWQ6ASpCHaoCGkVuZm9uaWNhLk51bWJlcmlu",
            "Zy5WMUJldGExYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Enfonica.Numbering.V1Beta1.PhoneNumbersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance), global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Parser, new[]{ "Name", "PhoneNumber", "DisplayName", "Labels", "IncomingMessageHandlerUris", "IncomingCallHandlerUris", "CreateTime", "DeleteTime", "LifecycleState" }, null, new[]{ typeof(global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState) }, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.CreatePhoneNumberInstanceRequest), global::Enfonica.Numbering.V1Beta1.CreatePhoneNumberInstanceRequest.Parser, new[]{ "Parent", "PhoneNumberInstance" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.GetPhoneNumberInstanceRequest), global::Enfonica.Numbering.V1Beta1.GetPhoneNumberInstanceRequest.Parser, new[]{ "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.ListPhoneNumberInstancesRequest), global::Enfonica.Numbering.V1Beta1.ListPhoneNumberInstancesRequest.Parser, new[]{ "Parent", "PageSize", "PageToken", "Prefix", "IncludeDeleted" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.ListPhoneNumberInstancesResponse), global::Enfonica.Numbering.V1Beta1.ListPhoneNumberInstancesResponse.Parser, new[]{ "PhoneNumberInstances", "NextPageToken" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.UpdatePhoneNumberInstanceRequest), global::Enfonica.Numbering.V1Beta1.UpdatePhoneNumberInstanceRequest.Parser, new[]{ "Name", "PhoneNumberInstance", "UpdateMask" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.DeletePhoneNumberInstanceRequest), global::Enfonica.Numbering.V1Beta1.DeletePhoneNumberInstanceRequest.Parser, new[]{ "Name" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Enfonica.Numbering.V1Beta1.GetProvisionedPhoneNumberInstanceRequest), global::Enfonica.Numbering.V1Beta1.GetProvisionedPhoneNumberInstanceRequest.Parser, new[]{ "Parent", "PhoneNumber" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The PhoneNumberInstance resource.
  /// </summary>
  public sealed partial class PhoneNumberInstance : pb::IMessage<PhoneNumberInstance>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PhoneNumberInstance> _parser = new pb::MessageParser<PhoneNumberInstance>(() => new PhoneNumberInstance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PhoneNumberInstance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PhoneNumberInstance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PhoneNumberInstance(PhoneNumberInstance other) : this() {
      name_ = other.name_;
      phoneNumber_ = other.phoneNumber_ != null ? other.phoneNumber_.Clone() : null;
      displayName_ = other.displayName_;
      labels_ = other.labels_.Clone();
      incomingMessageHandlerUris_ = other.incomingMessageHandlerUris_.Clone();
      incomingCallHandlerUris_ = other.incomingCallHandlerUris_.Clone();
      createTime_ = other.createTime_ != null ? other.createTime_.Clone() : null;
      deleteTime_ = other.deleteTime_ != null ? other.deleteTime_.Clone() : null;
      lifecycleState_ = other.lifecycleState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PhoneNumberInstance Clone() {
      return new PhoneNumberInstance(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Resource name of the phone number instance. It must match the pattern
    /// `projects/*/phoneNumberInstances/*`
    /// Output only.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_number" field.</summary>
    public const int PhoneNumberFieldNumber = 2;
    private global::Enfonica.Numbering.V1Beta1.PhoneNumber phoneNumber_;
    /// <summary>
    /// The phone number associated with the instance.
    /// Can only be set on creation.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Enfonica.Numbering.V1Beta1.PhoneNumber PhoneNumber {
      get { return phoneNumber_; }
      set {
        phoneNumber_ = value;
      }
    }

    /// <summary>Field number for the "display_name" field.</summary>
    public const int DisplayNameFieldNumber = 3;
    private string displayName_ = "";
    /// <summary>
    /// The display name of the phone number for use in the UI.
    /// Optional. Max length 100 characters.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DisplayName {
      get { return displayName_; }
      set {
        displayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "labels" field.</summary>
    public const int LabelsFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_labels_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> labels_ = new pbc::MapField<string, string>();
    /// <summary>
    /// The labels associated with the phone number.
    /// Max key length 100.  Max value length 1000. Max keys 50.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Labels {
      get { return labels_; }
    }

    /// <summary>Field number for the "incoming_message_handler_uris" field.</summary>
    public const int IncomingMessageHandlerUrisFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_incomingMessageHandlerUris_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> incomingMessageHandlerUris_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of URIs in priority order where incoming messages will be sent to.
    ///
    /// The first URI is the primary, and the subsequent URIs are used in order
    /// if the previous URIs fail.  If no URIs are specified, then no action is
    /// taken when receiving messages.
    ///
    /// Currently URIs must be fully qualified HTTP/HTTPS URLs, but this may change
    /// to include other types of URIs.
    ///
    /// Maximum 5 URIs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> IncomingMessageHandlerUris {
      get { return incomingMessageHandlerUris_; }
    }

    /// <summary>Field number for the "incoming_call_handler_uris" field.</summary>
    public const int IncomingCallHandlerUrisFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_incomingCallHandlerUris_codec
        = pb::FieldCodec.ForString(50);
    private readonly pbc::RepeatedField<string> incomingCallHandlerUris_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// List of URIs in priority order that will be executed for incoming calls.
    ///
    /// The first URI is the primary, and the subsequent URIs are used in order
    /// if the previous URIs fail.  If no URIs are specified, then no action is
    /// taken when receiving messages.
    ///
    /// Currently URIs must be fully qualified HTTP/HTTPS URLs, but this may change
    /// to include other types of URIs.
    ///
    /// Maximum 5 URIs.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> IncomingCallHandlerUris {
      get { return incomingCallHandlerUris_; }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 10;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createTime_;
    /// <summary>
    /// The creation time of the phone number instance.
    /// Output only.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "delete_time" field.</summary>
    public const int DeleteTimeFieldNumber = 11;
    private global::Google.Protobuf.WellKnownTypes.Timestamp deleteTime_;
    /// <summary>
    /// The deletion time of the phone number instance, if it has been deleted.
    /// Output only.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DeleteTime {
      get { return deleteTime_; }
      set {
        deleteTime_ = value;
      }
    }

    /// <summary>Field number for the "lifecycle_state" field.</summary>
    public const int LifecycleStateFieldNumber = 12;
    private global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState lifecycleState_ = global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState.Unknown;
    /// <summary>
    /// The state of the phone number instance in its lifecycle.
    /// Output only.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState LifecycleState {
      get { return lifecycleState_; }
      set {
        lifecycleState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PhoneNumberInstance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PhoneNumberInstance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(PhoneNumber, other.PhoneNumber)) return false;
      if (DisplayName != other.DisplayName) return false;
      if (!Labels.Equals(other.Labels)) return false;
      if(!incomingMessageHandlerUris_.Equals(other.incomingMessageHandlerUris_)) return false;
      if(!incomingCallHandlerUris_.Equals(other.incomingCallHandlerUris_)) return false;
      if (!object.Equals(CreateTime, other.CreateTime)) return false;
      if (!object.Equals(DeleteTime, other.DeleteTime)) return false;
      if (LifecycleState != other.LifecycleState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (phoneNumber_ != null) hash ^= PhoneNumber.GetHashCode();
      if (DisplayName.Length != 0) hash ^= DisplayName.GetHashCode();
      hash ^= Labels.GetHashCode();
      hash ^= incomingMessageHandlerUris_.GetHashCode();
      hash ^= incomingCallHandlerUris_.GetHashCode();
      if (createTime_ != null) hash ^= CreateTime.GetHashCode();
      if (deleteTime_ != null) hash ^= DeleteTime.GetHashCode();
      if (LifecycleState != global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState.Unknown) hash ^= LifecycleState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (phoneNumber_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PhoneNumber);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DisplayName);
      }
      labels_.WriteTo(output, _map_labels_codec);
      incomingMessageHandlerUris_.WriteTo(output, _repeated_incomingMessageHandlerUris_codec);
      incomingCallHandlerUris_.WriteTo(output, _repeated_incomingCallHandlerUris_codec);
      if (createTime_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(CreateTime);
      }
      if (deleteTime_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(DeleteTime);
      }
      if (LifecycleState != global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState.Unknown) {
        output.WriteRawTag(96);
        output.WriteEnum((int) LifecycleState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (phoneNumber_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PhoneNumber);
      }
      if (DisplayName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DisplayName);
      }
      labels_.WriteTo(ref output, _map_labels_codec);
      incomingMessageHandlerUris_.WriteTo(ref output, _repeated_incomingMessageHandlerUris_codec);
      incomingCallHandlerUris_.WriteTo(ref output, _repeated_incomingCallHandlerUris_codec);
      if (createTime_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(CreateTime);
      }
      if (deleteTime_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(DeleteTime);
      }
      if (LifecycleState != global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState.Unknown) {
        output.WriteRawTag(96);
        output.WriteEnum((int) LifecycleState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (phoneNumber_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PhoneNumber);
      }
      if (DisplayName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DisplayName);
      }
      size += labels_.CalculateSize(_map_labels_codec);
      size += incomingMessageHandlerUris_.CalculateSize(_repeated_incomingMessageHandlerUris_codec);
      size += incomingCallHandlerUris_.CalculateSize(_repeated_incomingCallHandlerUris_codec);
      if (createTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateTime);
      }
      if (deleteTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeleteTime);
      }
      if (LifecycleState != global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) LifecycleState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PhoneNumberInstance other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.phoneNumber_ != null) {
        if (phoneNumber_ == null) {
          PhoneNumber = new global::Enfonica.Numbering.V1Beta1.PhoneNumber();
        }
        PhoneNumber.MergeFrom(other.PhoneNumber);
      }
      if (other.DisplayName.Length != 0) {
        DisplayName = other.DisplayName;
      }
      labels_.Add(other.labels_);
      incomingMessageHandlerUris_.Add(other.incomingMessageHandlerUris_);
      incomingCallHandlerUris_.Add(other.incomingCallHandlerUris_);
      if (other.createTime_ != null) {
        if (createTime_ == null) {
          CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateTime.MergeFrom(other.CreateTime);
      }
      if (other.deleteTime_ != null) {
        if (deleteTime_ == null) {
          DeleteTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DeleteTime.MergeFrom(other.DeleteTime);
      }
      if (other.LifecycleState != global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState.Unknown) {
        LifecycleState = other.LifecycleState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (phoneNumber_ == null) {
              PhoneNumber = new global::Enfonica.Numbering.V1Beta1.PhoneNumber();
            }
            input.ReadMessage(PhoneNumber);
            break;
          }
          case 26: {
            DisplayName = input.ReadString();
            break;
          }
          case 34: {
            labels_.AddEntriesFrom(input, _map_labels_codec);
            break;
          }
          case 42: {
            incomingMessageHandlerUris_.AddEntriesFrom(input, _repeated_incomingMessageHandlerUris_codec);
            break;
          }
          case 50: {
            incomingCallHandlerUris_.AddEntriesFrom(input, _repeated_incomingCallHandlerUris_codec);
            break;
          }
          case 82: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 90: {
            if (deleteTime_ == null) {
              DeleteTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeleteTime);
            break;
          }
          case 96: {
            LifecycleState = (global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (phoneNumber_ == null) {
              PhoneNumber = new global::Enfonica.Numbering.V1Beta1.PhoneNumber();
            }
            input.ReadMessage(PhoneNumber);
            break;
          }
          case 26: {
            DisplayName = input.ReadString();
            break;
          }
          case 34: {
            labels_.AddEntriesFrom(ref input, _map_labels_codec);
            break;
          }
          case 42: {
            incomingMessageHandlerUris_.AddEntriesFrom(ref input, _repeated_incomingMessageHandlerUris_codec);
            break;
          }
          case 50: {
            incomingCallHandlerUris_.AddEntriesFrom(ref input, _repeated_incomingCallHandlerUris_codec);
            break;
          }
          case 82: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 90: {
            if (deleteTime_ == null) {
              DeleteTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeleteTime);
            break;
          }
          case 96: {
            LifecycleState = (global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Types.LifecycleState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PhoneNumberInstance message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// Lifecycle states of phone number instances.
      /// </summary>
      public enum LifecycleState {
        /// <summary>
        /// Unspecified lifecycle state.
        /// </summary>
        [pbr::OriginalName("LIFECYCLE_STATE_UNKNOWN")] Unknown = 0,
        /// <summary>
        /// The phone number instance is active and can be used.
        /// </summary>
        [pbr::OriginalName("ACTIVE")] Active = 1,
        /// <summary>
        /// The phone number instance has been deleted.
        /// </summary>
        [pbr::OriginalName("DELETED")] Deleted = 2,
        /// <summary>
        /// The phone number instance has been suspended.
        /// </summary>
        [pbr::OriginalName("SUSPENDED")] Suspended = 3,
      }

    }
    #endregion

  }

  /// <summary>
  /// Request to create a new phone number instance.
  /// </summary>
  public sealed partial class CreatePhoneNumberInstanceRequest : pb::IMessage<CreatePhoneNumberInstanceRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreatePhoneNumberInstanceRequest> _parser = new pb::MessageParser<CreatePhoneNumberInstanceRequest>(() => new CreatePhoneNumberInstanceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreatePhoneNumberInstanceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreatePhoneNumberInstanceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreatePhoneNumberInstanceRequest(CreatePhoneNumberInstanceRequest other) : this() {
      parent_ = other.parent_;
      phoneNumberInstance_ = other.phoneNumberInstance_ != null ? other.phoneNumberInstance_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreatePhoneNumberInstanceRequest Clone() {
      return new CreatePhoneNumberInstanceRequest(this);
    }

    /// <summary>Field number for the "parent" field.</summary>
    public const int ParentFieldNumber = 1;
    private string parent_ = "";
    /// <summary>
    /// The project under which to create the phone number instance
    /// in the form `projects/*`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parent {
      get { return parent_; }
      set {
        parent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_number_instance" field.</summary>
    public const int PhoneNumberInstanceFieldNumber = 2;
    private global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance phoneNumberInstance_;
    /// <summary>
    /// The phone number resource to be created.
    /// At minimum, you must supply `phone_number.phone_number`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance PhoneNumberInstance {
      get { return phoneNumberInstance_; }
      set {
        phoneNumberInstance_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreatePhoneNumberInstanceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreatePhoneNumberInstanceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Parent != other.Parent) return false;
      if (!object.Equals(PhoneNumberInstance, other.PhoneNumberInstance)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Parent.Length != 0) hash ^= Parent.GetHashCode();
      if (phoneNumberInstance_ != null) hash ^= PhoneNumberInstance.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (phoneNumberInstance_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PhoneNumberInstance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (phoneNumberInstance_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PhoneNumberInstance);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Parent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parent);
      }
      if (phoneNumberInstance_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PhoneNumberInstance);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreatePhoneNumberInstanceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Parent.Length != 0) {
        Parent = other.Parent;
      }
      if (other.phoneNumberInstance_ != null) {
        if (phoneNumberInstance_ == null) {
          PhoneNumberInstance = new global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance();
        }
        PhoneNumberInstance.MergeFrom(other.PhoneNumberInstance);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            if (phoneNumberInstance_ == null) {
              PhoneNumberInstance = new global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance();
            }
            input.ReadMessage(PhoneNumberInstance);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            if (phoneNumberInstance_ == null) {
              PhoneNumberInstance = new global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance();
            }
            input.ReadMessage(PhoneNumberInstance);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The GetPhoneNumberInstance request message.
  /// </summary>
  public sealed partial class GetPhoneNumberInstanceRequest : pb::IMessage<GetPhoneNumberInstanceRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetPhoneNumberInstanceRequest> _parser = new pb::MessageParser<GetPhoneNumberInstanceRequest>(() => new GetPhoneNumberInstanceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetPhoneNumberInstanceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPhoneNumberInstanceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPhoneNumberInstanceRequest(GetPhoneNumberInstanceRequest other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetPhoneNumberInstanceRequest Clone() {
      return new GetPhoneNumberInstanceRequest(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The resource name of the phone number instance to retrieve.
    /// Must be of the form `projects/*/phoneNumberInstances/*`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetPhoneNumberInstanceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetPhoneNumberInstanceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetPhoneNumberInstanceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The ListPhoneNumberInstances request.
  /// </summary>
  public sealed partial class ListPhoneNumberInstancesRequest : pb::IMessage<ListPhoneNumberInstancesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ListPhoneNumberInstancesRequest> _parser = new pb::MessageParser<ListPhoneNumberInstancesRequest>(() => new ListPhoneNumberInstancesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListPhoneNumberInstancesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPhoneNumberInstancesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPhoneNumberInstancesRequest(ListPhoneNumberInstancesRequest other) : this() {
      parent_ = other.parent_;
      pageSize_ = other.pageSize_;
      pageToken_ = other.pageToken_;
      prefix_ = other.prefix_;
      includeDeleted_ = other.includeDeleted_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPhoneNumberInstancesRequest Clone() {
      return new ListPhoneNumberInstancesRequest(this);
    }

    /// <summary>Field number for the "parent" field.</summary>
    public const int ParentFieldNumber = 1;
    private string parent_ = "";
    /// <summary>
    /// The project under which to list phone number instance, in the form `projects/*`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parent {
      get { return parent_; }
      set {
        parent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "page_size" field.</summary>
    public const int PageSizeFieldNumber = 2;
    private int pageSize_;
    /// <summary>
    /// The maximum number of phone number instance to return in the response.
    /// Optional, with a default value of 10 and maximum value of 100.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PageSize {
      get { return pageSize_; }
      set {
        pageSize_ = value;
      }
    }

    /// <summary>Field number for the "page_token" field.</summary>
    public const int PageTokenFieldNumber = 3;
    private string pageToken_ = "";
    /// <summary>
    /// A pagination token returned from a previous call to `ListPhoneNumberInstances`
    /// that indicates where this listing should continue from.
    /// Optional.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PageToken {
      get { return pageToken_; }
      set {
        pageToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "prefix" field.</summary>
    public const int PrefixFieldNumber = 4;
    private string prefix_ = "";
    /// <summary>
    /// The prefix, either in E164 or 0NSN, of numbers to retrieve.
    /// Optional.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Prefix {
      get { return prefix_; }
      set {
        prefix_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "include_deleted" field.</summary>
    public const int IncludeDeletedFieldNumber = 5;
    private bool includeDeleted_;
    /// <summary>
    /// Whether to include deleted phone numbers in the response.
    /// Optional (default false).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IncludeDeleted {
      get { return includeDeleted_; }
      set {
        includeDeleted_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListPhoneNumberInstancesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListPhoneNumberInstancesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Parent != other.Parent) return false;
      if (PageSize != other.PageSize) return false;
      if (PageToken != other.PageToken) return false;
      if (Prefix != other.Prefix) return false;
      if (IncludeDeleted != other.IncludeDeleted) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Parent.Length != 0) hash ^= Parent.GetHashCode();
      if (PageSize != 0) hash ^= PageSize.GetHashCode();
      if (PageToken.Length != 0) hash ^= PageToken.GetHashCode();
      if (Prefix.Length != 0) hash ^= Prefix.GetHashCode();
      if (IncludeDeleted != false) hash ^= IncludeDeleted.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
      if (PageToken.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PageToken);
      }
      if (Prefix.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Prefix);
      }
      if (IncludeDeleted != false) {
        output.WriteRawTag(40);
        output.WriteBool(IncludeDeleted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (PageSize != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(PageSize);
      }
      if (PageToken.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PageToken);
      }
      if (Prefix.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Prefix);
      }
      if (IncludeDeleted != false) {
        output.WriteRawTag(40);
        output.WriteBool(IncludeDeleted);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Parent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parent);
      }
      if (PageSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageSize);
      }
      if (PageToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PageToken);
      }
      if (Prefix.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Prefix);
      }
      if (IncludeDeleted != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListPhoneNumberInstancesRequest other) {
      if (other == null) {
        return;
      }
      if (other.Parent.Length != 0) {
        Parent = other.Parent;
      }
      if (other.PageSize != 0) {
        PageSize = other.PageSize;
      }
      if (other.PageToken.Length != 0) {
        PageToken = other.PageToken;
      }
      if (other.Prefix.Length != 0) {
        Prefix = other.Prefix;
      }
      if (other.IncludeDeleted != false) {
        IncludeDeleted = other.IncludeDeleted;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
          case 26: {
            PageToken = input.ReadString();
            break;
          }
          case 34: {
            Prefix = input.ReadString();
            break;
          }
          case 40: {
            IncludeDeleted = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 16: {
            PageSize = input.ReadInt32();
            break;
          }
          case 26: {
            PageToken = input.ReadString();
            break;
          }
          case 34: {
            Prefix = input.ReadString();
            break;
          }
          case 40: {
            IncludeDeleted = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The ListPhoneNumberInstances response.
  /// </summary>
  public sealed partial class ListPhoneNumberInstancesResponse : pb::IMessage<ListPhoneNumberInstancesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ListPhoneNumberInstancesResponse> _parser = new pb::MessageParser<ListPhoneNumberInstancesResponse>(() => new ListPhoneNumberInstancesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ListPhoneNumberInstancesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPhoneNumberInstancesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPhoneNumberInstancesResponse(ListPhoneNumberInstancesResponse other) : this() {
      phoneNumberInstances_ = other.phoneNumberInstances_.Clone();
      nextPageToken_ = other.nextPageToken_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ListPhoneNumberInstancesResponse Clone() {
      return new ListPhoneNumberInstancesResponse(this);
    }

    /// <summary>Field number for the "phone_number_instances" field.</summary>
    public const int PhoneNumberInstancesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance> _repeated_phoneNumberInstances_codec
        = pb::FieldCodec.ForMessage(10, global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance.Parser);
    private readonly pbc::RepeatedField<global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance> phoneNumberInstances_ = new pbc::RepeatedField<global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance>();
    /// <summary>
    /// A possibly paginated list of phone number instance that are direct descendants of
    /// the specified parent resource.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance> PhoneNumberInstances {
      get { return phoneNumberInstances_; }
    }

    /// <summary>Field number for the "next_page_token" field.</summary>
    public const int NextPageTokenFieldNumber = 2;
    private string nextPageToken_ = "";
    /// <summary>
    /// A pagination token returned from a previous call to `ListPhoneNumberInstances`
    /// that indicates from where listing should continue.
    /// Optional.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NextPageToken {
      get { return nextPageToken_; }
      set {
        nextPageToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ListPhoneNumberInstancesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ListPhoneNumberInstancesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!phoneNumberInstances_.Equals(other.phoneNumberInstances_)) return false;
      if (NextPageToken != other.NextPageToken) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= phoneNumberInstances_.GetHashCode();
      if (NextPageToken.Length != 0) hash ^= NextPageToken.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      phoneNumberInstances_.WriteTo(output, _repeated_phoneNumberInstances_codec);
      if (NextPageToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NextPageToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      phoneNumberInstances_.WriteTo(ref output, _repeated_phoneNumberInstances_codec);
      if (NextPageToken.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(NextPageToken);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += phoneNumberInstances_.CalculateSize(_repeated_phoneNumberInstances_codec);
      if (NextPageToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NextPageToken);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ListPhoneNumberInstancesResponse other) {
      if (other == null) {
        return;
      }
      phoneNumberInstances_.Add(other.phoneNumberInstances_);
      if (other.NextPageToken.Length != 0) {
        NextPageToken = other.NextPageToken;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            phoneNumberInstances_.AddEntriesFrom(input, _repeated_phoneNumberInstances_codec);
            break;
          }
          case 18: {
            NextPageToken = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            phoneNumberInstances_.AddEntriesFrom(ref input, _repeated_phoneNumberInstances_codec);
            break;
          }
          case 18: {
            NextPageToken = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The request message for updating a phonenumberinstance's properties.
  /// </summary>
  public sealed partial class UpdatePhoneNumberInstanceRequest : pb::IMessage<UpdatePhoneNumberInstanceRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<UpdatePhoneNumberInstanceRequest> _parser = new pb::MessageParser<UpdatePhoneNumberInstanceRequest>(() => new UpdatePhoneNumberInstanceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdatePhoneNumberInstanceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdatePhoneNumberInstanceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdatePhoneNumberInstanceRequest(UpdatePhoneNumberInstanceRequest other) : this() {
      name_ = other.name_;
      phoneNumberInstance_ = other.phoneNumberInstance_ != null ? other.phoneNumberInstance_.Clone() : null;
      updateMask_ = other.updateMask_ != null ? other.updateMask_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdatePhoneNumberInstanceRequest Clone() {
      return new UpdatePhoneNumberInstanceRequest(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The name of the phone number instance to be updated.
    /// Must be of the form `projects/*/phoneNumberInstances/*`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_number_instance" field.</summary>
    public const int PhoneNumberInstanceFieldNumber = 2;
    private global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance phoneNumberInstance_;
    /// <summary>
    /// The new definition of the PhoneNumberInstance.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance PhoneNumberInstance {
      get { return phoneNumberInstance_; }
      set {
        phoneNumberInstance_ = value;
      }
    }

    /// <summary>Field number for the "update_mask" field.</summary>
    public const int UpdateMaskFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.FieldMask updateMask_;
    /// <summary>
    /// Fields to be updated.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.FieldMask UpdateMask {
      get { return updateMask_; }
      set {
        updateMask_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdatePhoneNumberInstanceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdatePhoneNumberInstanceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(PhoneNumberInstance, other.PhoneNumberInstance)) return false;
      if (!object.Equals(UpdateMask, other.UpdateMask)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (phoneNumberInstance_ != null) hash ^= PhoneNumberInstance.GetHashCode();
      if (updateMask_ != null) hash ^= UpdateMask.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (phoneNumberInstance_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PhoneNumberInstance);
      }
      if (updateMask_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (phoneNumberInstance_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PhoneNumberInstance);
      }
      if (updateMask_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateMask);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (phoneNumberInstance_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PhoneNumberInstance);
      }
      if (updateMask_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateMask);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdatePhoneNumberInstanceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.phoneNumberInstance_ != null) {
        if (phoneNumberInstance_ == null) {
          PhoneNumberInstance = new global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance();
        }
        PhoneNumberInstance.MergeFrom(other.PhoneNumberInstance);
      }
      if (other.updateMask_ != null) {
        if (updateMask_ == null) {
          UpdateMask = new global::Google.Protobuf.WellKnownTypes.FieldMask();
        }
        UpdateMask.MergeFrom(other.UpdateMask);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (phoneNumberInstance_ == null) {
              PhoneNumberInstance = new global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance();
            }
            input.ReadMessage(PhoneNumberInstance);
            break;
          }
          case 26: {
            if (updateMask_ == null) {
              UpdateMask = new global::Google.Protobuf.WellKnownTypes.FieldMask();
            }
            input.ReadMessage(UpdateMask);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (phoneNumberInstance_ == null) {
              PhoneNumberInstance = new global::Enfonica.Numbering.V1Beta1.PhoneNumberInstance();
            }
            input.ReadMessage(PhoneNumberInstance);
            break;
          }
          case 26: {
            if (updateMask_ == null) {
              UpdateMask = new global::Google.Protobuf.WellKnownTypes.FieldMask();
            }
            input.ReadMessage(UpdateMask);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The DeletePhoneNumberInstance request message.
  /// </summary>
  public sealed partial class DeletePhoneNumberInstanceRequest : pb::IMessage<DeletePhoneNumberInstanceRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<DeletePhoneNumberInstanceRequest> _parser = new pb::MessageParser<DeletePhoneNumberInstanceRequest>(() => new DeletePhoneNumberInstanceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DeletePhoneNumberInstanceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeletePhoneNumberInstanceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeletePhoneNumberInstanceRequest(DeletePhoneNumberInstanceRequest other) : this() {
      name_ = other.name_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DeletePhoneNumberInstanceRequest Clone() {
      return new DeletePhoneNumberInstanceRequest(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// The resource name of the phone number instance to be deleted.
    /// Must be of the form `projects/*/phoneNumberInstances/*`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DeletePhoneNumberInstanceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DeletePhoneNumberInstanceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DeletePhoneNumberInstanceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// The GetProvisionedPhoneNumberInstance request message.
  /// </summary>
  public sealed partial class GetProvisionedPhoneNumberInstanceRequest : pb::IMessage<GetProvisionedPhoneNumberInstanceRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetProvisionedPhoneNumberInstanceRequest> _parser = new pb::MessageParser<GetProvisionedPhoneNumberInstanceRequest>(() => new GetProvisionedPhoneNumberInstanceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetProvisionedPhoneNumberInstanceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Enfonica.Numbering.V1Beta1.PhoneNumberInstancesReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProvisionedPhoneNumberInstanceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProvisionedPhoneNumberInstanceRequest(GetProvisionedPhoneNumberInstanceRequest other) : this() {
      parent_ = other.parent_;
      phoneNumber_ = other.phoneNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetProvisionedPhoneNumberInstanceRequest Clone() {
      return new GetProvisionedPhoneNumberInstanceRequest(this);
    }

    /// <summary>Field number for the "parent" field.</summary>
    public const int ParentFieldNumber = 1;
    private string parent_ = "";
    /// <summary>
    /// The parent to search under. This must be set as
    /// `projects/-`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Parent {
      get { return parent_; }
      set {
        parent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "phone_number" field.</summary>
    public const int PhoneNumberFieldNumber = 2;
    private string phoneNumber_ = "";
    /// <summary>
    /// The phone number of the instance to find, in +E164.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PhoneNumber {
      get { return phoneNumber_; }
      set {
        phoneNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetProvisionedPhoneNumberInstanceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetProvisionedPhoneNumberInstanceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Parent != other.Parent) return false;
      if (PhoneNumber != other.PhoneNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Parent.Length != 0) hash ^= Parent.GetHashCode();
      if (PhoneNumber.Length != 0) hash ^= PhoneNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PhoneNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Parent.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Parent);
      }
      if (PhoneNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(PhoneNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Parent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Parent);
      }
      if (PhoneNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PhoneNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetProvisionedPhoneNumberInstanceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Parent.Length != 0) {
        Parent = other.Parent;
      }
      if (other.PhoneNumber.Length != 0) {
        PhoneNumber = other.PhoneNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            PhoneNumber = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Parent = input.ReadString();
            break;
          }
          case 18: {
            PhoneNumber = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
