// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enfonica/voice/v1beta1/transcriptions.proto
// </auto-generated>
// Original file comments:
// Copyright 2021 Enfonica Pty Ltd
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Enfonica.Voice.V1Beta1 {
  /// <summary>
  /// Manages Transcriptions.
  /// </summary>
  public static partial class Transcriptions
  {
    static readonly string __ServiceName = "enfonica.voice.v1beta1.Transcriptions";

    static readonly grpc::Marshaller<global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest> __Marshaller_enfonica_voice_v1beta1_GetTranscriptionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Enfonica.Voice.V1Beta1.Transcription> __Marshaller_enfonica_voice_v1beta1_Transcription = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Enfonica.Voice.V1Beta1.Transcription.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest> __Marshaller_enfonica_voice_v1beta1_ListTranscriptionsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse> __Marshaller_enfonica_voice_v1beta1_ListTranscriptionsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest> __Marshaller_enfonica_voice_v1beta1_DeleteTranscriptionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest, global::Enfonica.Voice.V1Beta1.Transcription> __Method_GetTranscription = new grpc::Method<global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest, global::Enfonica.Voice.V1Beta1.Transcription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetTranscription",
        __Marshaller_enfonica_voice_v1beta1_GetTranscriptionRequest,
        __Marshaller_enfonica_voice_v1beta1_Transcription);

    static readonly grpc::Method<global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest, global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse> __Method_ListTranscriptions = new grpc::Method<global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest, global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListTranscriptions",
        __Marshaller_enfonica_voice_v1beta1_ListTranscriptionsRequest,
        __Marshaller_enfonica_voice_v1beta1_ListTranscriptionsResponse);

    static readonly grpc::Method<global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteTranscription = new grpc::Method<global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteTranscription",
        __Marshaller_enfonica_voice_v1beta1_DeleteTranscriptionRequest,
        __Marshaller_google_protobuf_Empty);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Enfonica.Voice.V1Beta1.TranscriptionsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Transcriptions</summary>
    [grpc::BindServiceMethod(typeof(Transcriptions), "BindService")]
    public abstract partial class TranscriptionsBase
    {
      /// <summary>
      /// Retrieves a Transcription identified by the supplied resource name.
      ///
      /// The caller must have `voice.transcriptions.get` permission on the project.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Enfonica.Voice.V1Beta1.Transcription> GetTranscription(global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Lists the Transcriptions of the specified project.
      /// List returns Transcriptions sorted by create_time descending.
      ///
      /// The caller must have `voice.transcriptions.list` permission on the project.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse> ListTranscriptions(global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Deletes a transcription.
      ///
      /// The caller must have `voice.transcriptions.delete` permission on the project.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTranscription(global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Transcriptions</summary>
    public partial class TranscriptionsClient : grpc::ClientBase<TranscriptionsClient>
    {
      /// <summary>Creates a new client for Transcriptions</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TranscriptionsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Transcriptions that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TranscriptionsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TranscriptionsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TranscriptionsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Retrieves a Transcription identified by the supplied resource name.
      ///
      /// The caller must have `voice.transcriptions.get` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Enfonica.Voice.V1Beta1.Transcription GetTranscription(global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTranscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves a Transcription identified by the supplied resource name.
      ///
      /// The caller must have `voice.transcriptions.get` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Enfonica.Voice.V1Beta1.Transcription GetTranscription(global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetTranscription, null, options, request);
      }
      /// <summary>
      /// Retrieves a Transcription identified by the supplied resource name.
      ///
      /// The caller must have `voice.transcriptions.get` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Enfonica.Voice.V1Beta1.Transcription> GetTranscriptionAsync(global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetTranscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Retrieves a Transcription identified by the supplied resource name.
      ///
      /// The caller must have `voice.transcriptions.get` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Enfonica.Voice.V1Beta1.Transcription> GetTranscriptionAsync(global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetTranscription, null, options, request);
      }
      /// <summary>
      /// Lists the Transcriptions of the specified project.
      /// List returns Transcriptions sorted by create_time descending.
      ///
      /// The caller must have `voice.transcriptions.list` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse ListTranscriptions(global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListTranscriptions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists the Transcriptions of the specified project.
      /// List returns Transcriptions sorted by create_time descending.
      ///
      /// The caller must have `voice.transcriptions.list` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse ListTranscriptions(global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListTranscriptions, null, options, request);
      }
      /// <summary>
      /// Lists the Transcriptions of the specified project.
      /// List returns Transcriptions sorted by create_time descending.
      ///
      /// The caller must have `voice.transcriptions.list` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse> ListTranscriptionsAsync(global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListTranscriptionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists the Transcriptions of the specified project.
      /// List returns Transcriptions sorted by create_time descending.
      ///
      /// The caller must have `voice.transcriptions.list` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse> ListTranscriptionsAsync(global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListTranscriptions, null, options, request);
      }
      /// <summary>
      /// Deletes a transcription.
      ///
      /// The caller must have `voice.transcriptions.delete` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteTranscription(global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTranscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes a transcription.
      ///
      /// The caller must have `voice.transcriptions.delete` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteTranscription(global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteTranscription, null, options, request);
      }
      /// <summary>
      /// Deletes a transcription.
      ///
      /// The caller must have `voice.transcriptions.delete` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTranscriptionAsync(global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteTranscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes a transcription.
      ///
      /// The caller must have `voice.transcriptions.delete` permission on the project.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteTranscriptionAsync(global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteTranscription, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TranscriptionsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TranscriptionsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TranscriptionsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetTranscription, serviceImpl.GetTranscription)
          .AddMethod(__Method_ListTranscriptions, serviceImpl.ListTranscriptions)
          .AddMethod(__Method_DeleteTranscription, serviceImpl.DeleteTranscription).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TranscriptionsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetTranscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Enfonica.Voice.V1Beta1.GetTranscriptionRequest, global::Enfonica.Voice.V1Beta1.Transcription>(serviceImpl.GetTranscription));
      serviceBinder.AddMethod(__Method_ListTranscriptions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Enfonica.Voice.V1Beta1.ListTranscriptionsRequest, global::Enfonica.Voice.V1Beta1.ListTranscriptionsResponse>(serviceImpl.ListTranscriptions));
      serviceBinder.AddMethod(__Method_DeleteTranscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Enfonica.Voice.V1Beta1.DeleteTranscriptionRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteTranscription));
    }

  }
}
#endregion
